# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# cspell:ignore buildx getsentry sourcemaps gonuit

name: Publish a new release

on:
  push:
    branches: [master]

jobs:
  # Run Semantic Release only on master branch
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      # Get checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Node js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.10.0'

      # Install Dependencies
      - name: Install dependencies 🔧
        run: npm ci

      # Npm Run Check
      - name: Run Check All
        run: npm run check:all

      # Run Semantic Release
      - name: Semantic Release
        run: |
          npm i -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec @semantic-release/npm
          npx semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com

      # Checkout Develop
      - name: Checkout Develop
        uses: actions/checkout@v3
        with:
          ref: develop

      # Pull From `Master` to `Develop`
      - name: Pull From `Master` to `Develop`
        run: |
          git pull origin master
          git push
